version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-jake-test
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install -r requirements.txt
      - run:
          name: Validate we can run it
          command: pipenv run python main.py
      - run:
          name: Run Jake
          command: pipenv run jake ddt
